import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 20,
  },
  headerTitle: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 10,
  },
  textInput: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  submitButton: {
    width: "100%",
    marginTop: 20,
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
  },
  buttonSignUp: {
    width: "100%",
    height: 48,
    backgroundColor: "#FA8A34",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
  },
  buttonSignIn: {
    width: "100%",
    height: 48,
    backgroundColor: "",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 16,
  },
  buttonSignUpText: {
    fontSize: 15,
    color: "white",
  },
  buttonSignInText: { fontSize: 15, color: "#FA8A34" },
  arrowIcon: {
    width: 50,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "flex-start",
    marginVertical: 10,
    borderRadius: 20,
  },
  label: {
    fontSize: 15,
    marginLeft: 10,
    color: "#606773",
    alignSelf: "flex-start",
    marginVertical: 10,
  },
  labelError: {
    fontSize: 15,
    marginLeft: 10,
    color: "#ff1500",
    alignSelf: "flex-start",
    marginVertical: 10,
  },
  input: {
    position: "relative",
    width: "100%",
    justifyContent: "center",
    height: 56,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 8,
    color: "#333",
  },
  inputError: {
    position: "relative",
    justifyContent: "center",
    width: "100%",
    height: 56,
    borderColor: "#ff0000",
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 8,
    color: "#333",
  },
  InputIconEng: {
    position: "absolute",
    right: 10,
    top: -25,
  },
  InputIconArab: {
    position: "absolute",
    left: 10,
    top: -25,
  },
});

export default styles;

// const styles = StyleSheet.create({
//   container: {
//     flex: 1,
//     alignItems: "center",
//     paddingHorizontal: 20,
//   },
//   headerTitle: {
//     flexDirection: "row",
//     alignItems: "center",
//     alignSelf: "flex-start",
//     gap: 10,
//   },
//   textInput: {
//     width: "100%",
//     justifyContent: "center",
//     alignItems: "center",
//   },
//   submitButton: {
//     width: "100%",
//     marginTop: 20,
//     justifyContent: "center",
//     alignItems: "center",
//     gap: 10,
//   },
//   buttonSignUp: {
//     width: "100%",
//     height: 48,
//     backgroundColor: "#FA8A34",
//     alignItems: "center",
//     justifyContent: "center",
//     borderRadius: 16,
//   },
//   buttonSignIn: {
//     width: "100%",
//     height: 48,
//     backgroundColor: "",
//     alignItems: "center",
//     justifyContent: "center",
//     borderRadius: 16,
//   },
//   buttonSignUpText: {
//     fontSize: 15,
//     color: "white",
//   },
//   buttonSignInText: { fontSize: 15, color: "#FA8A34" },
//   arrowIcon: {
//     width: 50,
//     height: 50,
//     justifyContent: "center",
//     alignItems: "center",
//     alignSelf: "flex-start",
//     marginVertical: 10,
//     borderRadius: 20,
//   },
//   label: {
//     fontSize: 15,
//     marginLeft: 10,
//     color: "#606773",
//     alignSelf: "flex-start",
//     marginVertical: 10,
//   },
//   labelError: {
//     fontSize: 15,
//     marginLeft: 10,
//     color: "#ff1500",
//     alignSelf: "flex-start",
//     marginVertical: 10,
//   },
//   input: {
//     width: "100%",
//     justifyContent: "center",
//     height: 56,
//     borderColor: "#ccc",
//     borderWidth: 1,
//     borderRadius: 16,
//     paddingHorizontal: 8,
//     color: "#333",
//     position: "relative",
//   },
//   inputError: {
//     position: "relative",
//     justifyContent: "center",
//     width: "100%",
//     height: 56,
//     borderColor: "#ff0000",
//     borderWidth: 1,
//     borderRadius: 16,
//     paddingHorizontal: 8,
//     color: "#333",
//   },
//   InputIconEng: {
//     position: "absolute",
//     right: 10,
//     top: "50%",
//     transform: [{ translateY: -12 }],
//   },
//   InputIconArab: {
//     position: "absolute",
//     left: 10,
//     top: "50%",
//     transform: [{ translateY: -17 }],
//   },
// });

// export default styles;
